ft. gemini 2.0 provider
Huddle01/huddle01-ai pull request #4
Opened 2024-12-16 17:11 UTC by arcinston

2025-01-03 05:53 UTC, OmGuptaIND requested changes

2025-01-03 05:53 UTC, OmGuptaIND commented on ai01/providers/openai/realtime/realtime_model.py
> +            )
dont need to assign self._main_task() already did it in __init__ function

2025-01-03 11:13 UTC, arcinston commented on ai01/providers/openai/realtime/realtime_model.py
> +            )
hmm i dont remember writing this

@OmGuptaIND this is linting changes

2025-01-06 10:07 UTC, OmGuptaIND approved these changes

2025-01-06 10:07 UTC, merged